/* Generated by build/build-observatory-overlay.mjs.
 * Source snapshot: data/geopolitical-observatory-dashboard/
 * Upstream Geopolitical Observatory was inspected read-only and not modified.
 */
(function(){
  const overlay = {
  "meta": {
    "source": "CabinDioxide/geopolitical-observatory-dashboard",
    "sourceUrl": "https://github.com/CabinDioxide/geopolitical-observatory-dashboard",
    "vercelUrl": "https://geopolitical-observatory.vercel.app/",
    "lastRun": "2026-06-07T08:47:38.864841Z",
    "generatedAt": "2026-06-07T10:38:01.884Z",
    "flowCount": 160,
    "usableFlowCount": 62,
    "chokepointCount": 15,
    "note": "Read-only import into Stack Atlas. Upstream project was not modified."
  },
  "chokepoints": [
    {
      "id": "taiwan",
      "name_zh": "Taiwan Strait",
      "name_en": "Taiwan Strait",
      "pos": [
        831.9,
        183.3
      ],
      "evidence": "source-linked",
      "affectsCountries": [
        "TW",
        "CN",
        "JP"
      ],
      "affectsStacks": [
        "ai-compute"
      ],
      "note_zh": "Beyond shipping volume, the strait's significance is defined by Taiwan's dominance of advanced semiconductor fabrication (TSMC produces ~90% of sub-7nm chips). A blockade would be simultaneously a maritime, trade, and technology crisis.",
      "note_en": "Beyond shipping volume, the strait's significance is defined by Taiwan's dominance of advanced semiconductor fabrication (TSMC produces ~90% of sub-7nm chips). A blockade would be simultaneously a maritime, trade, and technology crisis."
    },
    {
      "id": "turkish-straits",
      "name_zh": "Turkish Straits (Bosphorus/Dardanelles)",
      "name_en": "Turkish Straits (Bosphorus/Dardanelles)",
      "pos": [
        580.6,
        135.8
      ],
      "evidence": "source-linked",
      "affectsCountries": [],
      "affectsStacks": [
        "energy"
      ],
      "note_zh": "Only maritime access from the Black Sea to the Mediterranean. Governed by the 1936 Montreux Convention, which gives Turkey control over warship transit. Critical for Russian naval power projection and grain/energy exports from the Black Sea region.",
      "note_en": "Only maritime access from the Black Sea to the Mediterranean. Governed by the 1936 Montreux Convention, which gives Turkey control over warship transit. Critical for Russian naval power projection and grain/energy exports from the Black Sea region."
    },
    {
      "id": "gibraltar",
      "name_zh": "Strait of Gibraltar",
      "name_en": "Strait of Gibraltar",
      "pos": [
        484.4,
        150.1
      ],
      "evidence": "source-linked",
      "affectsCountries": [
        "NL",
        "TW",
        "KR",
        "DE",
        "CN",
        "US"
      ],
      "affectsStacks": [
        "ai-compute",
        "energy"
      ],
      "note_zh": "Only natural connection between the Atlantic and Mediterranean. NATO controls both shores. Critical for Mediterranean trade access and US/European naval operations.",
      "note_en": "Only natural connection between the Atlantic and Mediterranean. NATO controls both shores. Critical for Mediterranean trade access and US/European naval operations."
    },
    {
      "id": "cape-good-hope",
      "name_zh": "Cape of Good Hope",
      "name_en": "Cape of Good Hope",
      "pos": [
        551.4,
        345.6
      ],
      "evidence": "source-linked",
      "affectsCountries": [
        "CN"
      ],
      "affectsStacks": [
        "energy"
      ],
      "note_zh": "Not a narrow strait but a strategic waypoint. Primary alternative when Suez or Bab el-Mandeb is disrupted, adding 10-14 days to Europe-Asia routes. Traffic surged significantly after 2024 Houthi attacks forced rerouting.",
      "note_en": "Not a narrow strait but a strategic waypoint. Primary alternative when Suez or Bab el-Mandeb is disrupted, adding 10-14 days to Europe-Asia routes. Traffic surged significantly after 2024 Houthi attacks forced rerouting."
    },
    {
      "id": "korea-tsushima",
      "name_zh": "Korea Strait / Tsushima Strait",
      "name_en": "Korea Strait / Tsushima Strait",
      "pos": [
        859.7,
        155.6
      ],
      "evidence": "source-linked",
      "affectsCountries": [
        "JP",
        "TW",
        "KR",
        "CN",
        "NL",
        "US",
        "SA",
        "IN",
        "QA"
      ],
      "affectsStacks": [
        "ai-compute",
        "energy"
      ],
      "note_zh": "Controls access between the Sea of Japan and the East China Sea. Critical for Russian Pacific Fleet movements from Vladivostok. Japan-Korea strategic competition adds political complexity to what is an essential trade corridor for Northeast Asia.",
      "note_en": "Controls access between the Sea of Japan and the East China Sea. Critical for Russian Pacific Fleet movements from Vladivostok. Japan-Korea strategic competition adds political complexity to what is an essential trade corridor for Northeast Asia."
    }
  ],
  "candidateAlerts": [
    {
      "id": "obs-flow-tw-cn-advanced-chips",
      "status": "needs-review",
      "priority": "high",
      "title_zh": "Taiwan → China: Advanced Semiconductor Chips",
      "title_en": "Taiwan -> China: Advanced Semiconductor Chips",
      "signal_zh": "来自 Geopolitical Observatory strategic_flows 的 critical 级候选流（2024，约 $52.0B）。先作为 Stack Atlas 线索点亮，证据定级仍需回源复核。",
      "signal_en": "Candidate critical flow from Geopolitical Observatory strategic_flows (2024, about $52.0B). Imported as a Stack Atlas lead; evidence grade still requires source review.",
      "relNodes": [
        "ac-fab",
        "ac-euv",
        "ac-gpu",
        "ac-hbm",
        "ac-eda"
      ],
      "relCountries": [
        "TW",
        "CN"
      ],
      "relCompanies": [],
      "relChokepoints": [
        "taiwan"
      ],
      "source": "geopolitical-observatory-dashboard",
      "sourceFlowId": "flow-tw-cn-advanced-chips"
    },
    {
      "id": "obs-flow-tw-us-advanced-chips",
      "status": "needs-review",
      "priority": "high",
      "title_zh": "Taiwan → United States: Leading-Edge Logic Chips",
      "title_en": "Taiwan -> United States: Leading-Edge Logic Chips",
      "signal_zh": "来自 Geopolitical Observatory strategic_flows 的 critical 级候选流（2024，约 $42.0B）。先作为 Stack Atlas 线索点亮，证据定级仍需回源复核。",
      "signal_en": "Candidate critical flow from Geopolitical Observatory strategic_flows (2024, about $42.0B). Imported as a Stack Atlas lead; evidence grade still requires source review.",
      "relNodes": [
        "ac-fab",
        "ac-euv",
        "ac-gpu",
        "ac-hbm",
        "ac-eda"
      ],
      "relCountries": [
        "TW",
        "US"
      ],
      "relCompanies": [],
      "relChokepoints": [],
      "source": "geopolitical-observatory-dashboard",
      "sourceFlowId": "flow-tw-us-advanced-chips"
    },
    {
      "id": "obs-flow-sa-jp-crude-oil",
      "status": "needs-review",
      "priority": "high",
      "title_zh": "Saudi Arabia → Japan: Crude Oil",
      "title_en": "Saudi Arabia -> Japan: Crude Oil",
      "signal_zh": "来自 Geopolitical Observatory strategic_flows 的 critical 级候选流（2024，约 $30.0B）。先作为 Stack Atlas 线索点亮，证据定级仍需回源复核。",
      "signal_en": "Candidate critical flow from Geopolitical Observatory strategic_flows (2024, about $30.0B). Imported as a Stack Atlas lead; evidence grade still requires source review.",
      "relNodes": [
        "en-crude",
        "en-tanker"
      ],
      "relCountries": [
        "SA",
        "JP"
      ],
      "relCompanies": [],
      "relChokepoints": [
        "hormuz",
        "malacca"
      ],
      "source": "geopolitical-observatory-dashboard",
      "sourceFlowId": "flow-sa-jp-crude-oil"
    },
    {
      "id": "obs-flow-tw-us-ai-gpu-chips-ac",
      "status": "needs-review",
      "priority": "high",
      "title_zh": "Taiwan → United States: AI GPU Chips (TSMC fab for Nvidia/AMD)",
      "title_en": "Taiwan -> United States: AI GPU Chips (TSMC fab for Nvidia/AMD)",
      "signal_zh": "来自 Geopolitical Observatory strategic_flows 的 critical 级候选流（2024，约 $25.0B）。先作为 Stack Atlas 线索点亮，证据定级仍需回源复核。",
      "signal_en": "Candidate critical flow from Geopolitical Observatory strategic_flows (2024, about $25.0B). Imported as a Stack Atlas lead; evidence grade still requires source review.",
      "relNodes": [
        "ac-power",
        "ac-gpu",
        "ac-cloud"
      ],
      "relCountries": [
        "TW",
        "US"
      ],
      "relCompanies": [],
      "relChokepoints": [],
      "source": "geopolitical-observatory-dashboard",
      "sourceFlowId": "flow-tw-us-ai-gpu-chips-ac"
    },
    {
      "id": "obs-flow-qa-jp-lng",
      "status": "needs-review",
      "priority": "high",
      "title_zh": "Qatar → Japan: Liquefied Natural Gas (LNG)",
      "title_en": "Qatar -> Japan: Liquefied Natural Gas (LNG)",
      "signal_zh": "来自 Geopolitical Observatory strategic_flows 的 critical 级候选流（2024，约 $18.0B）。先作为 Stack Atlas 线索点亮，证据定级仍需回源复核。",
      "signal_en": "Candidate critical flow from Geopolitical Observatory strategic_flows (2024, about $18.0B). Imported as a Stack Atlas lead; evidence grade still requires source review.",
      "relNodes": [
        "en-lng",
        "en-tanker"
      ],
      "relCountries": [
        "QA",
        "JP"
      ],
      "relCompanies": [],
      "relChokepoints": [
        "hormuz",
        "malacca"
      ],
      "source": "geopolitical-observatory-dashboard",
      "sourceFlowId": "flow-qa-jp-lng"
    },
    {
      "id": "obs-flow-kr-us-hbm-chips",
      "status": "needs-review",
      "priority": "high",
      "title_zh": "South Korea → United States: High Bandwidth Memory (HBM) for AI",
      "title_en": "South Korea -> United States: High Bandwidth Memory (HBM) for AI",
      "signal_zh": "来自 Geopolitical Observatory strategic_flows 的 critical 级候选流（2024，约 $12.0B）。先作为 Stack Atlas 线索点亮，证据定级仍需回源复核。",
      "signal_en": "Candidate critical flow from Geopolitical Observatory strategic_flows (2024, about $12.0B). Imported as a Stack Atlas lead; evidence grade still requires source review.",
      "relNodes": [
        "ac-fab",
        "ac-euv",
        "ac-gpu",
        "ac-hbm",
        "ac-eda"
      ],
      "relCountries": [
        "KR",
        "US"
      ],
      "relCompanies": [],
      "relChokepoints": [
        "korea-tsushima"
      ],
      "source": "geopolitical-observatory-dashboard",
      "sourceFlowId": "flow-kr-us-hbm-chips"
    },
    {
      "id": "obs-flow-kr-us-hbm-ai-ac",
      "status": "needs-review",
      "priority": "high",
      "title_zh": "South Korea → United States: HBM Memory for AI (SK Hynix)",
      "title_en": "South Korea -> United States: HBM Memory for AI (SK Hynix)",
      "signal_zh": "来自 Geopolitical Observatory strategic_flows 的 critical 级候选流（2024，约 $12.0B）。先作为 Stack Atlas 线索点亮，证据定级仍需回源复核。",
      "signal_en": "Candidate critical flow from Geopolitical Observatory strategic_flows (2024, about $12.0B). Imported as a Stack Atlas lead; evidence grade still requires source review.",
      "relNodes": [
        "ac-power",
        "ac-gpu",
        "ac-cloud"
      ],
      "relCountries": [
        "KR",
        "US"
      ],
      "relCompanies": [],
      "relChokepoints": [
        "korea-tsushima"
      ],
      "source": "geopolitical-observatory-dashboard",
      "sourceFlowId": "flow-kr-us-hbm-ai-ac"
    },
    {
      "id": "obs-flow-nl-tw-euv-lithography",
      "status": "needs-review",
      "priority": "high",
      "title_zh": "Netherlands → Taiwan: EUV Lithography Systems",
      "title_en": "Netherlands -> Taiwan: EUV Lithography Systems",
      "signal_zh": "来自 Geopolitical Observatory strategic_flows 的 critical 级候选流（2024，约 $9.5B）。先作为 Stack Atlas 线索点亮，证据定级仍需回源复核。",
      "signal_en": "Candidate critical flow from Geopolitical Observatory strategic_flows (2024, about $9.5B). Imported as a Stack Atlas lead; evidence grade still requires source review.",
      "relNodes": [
        "ac-fab",
        "ac-euv",
        "ac-gpu",
        "ac-hbm",
        "ac-eda"
      ],
      "relCountries": [
        "NL",
        "TW"
      ],
      "relCompanies": [],
      "relChokepoints": [
        "suez",
        "babelmandeb",
        "gibraltar"
      ],
      "source": "geopolitical-observatory-dashboard",
      "sourceFlowId": "flow-nl-tw-euv-lithography"
    }
  ]
};
  window.OBSERVATORY_OVERLAY = overlay;
  const D = window.ATLAS_DATA;
  if (!D) return;
  D.meta.observatoryOverlay = overlay.meta;
  const existingChokes = new Set((D.chokepoints || []).map(c => c.id));
  overlay.chokepoints.forEach(cp => {
    if (!existingChokes.has(cp.id)) D.chokepoints.push(cp);
  });
  const existingAlerts = new Set((D.candidateAlerts || []).map(a => a.id));
  overlay.candidateAlerts.forEach(alert => {
    if (!existingAlerts.has(alert.id)) D.candidateAlerts.push(alert);
  });
})();
